version: "2.2"
services:
  suite-base:
    build:
      context: .
      dockerfile: ./suite/Dockerfile
    volumes:
      - ..:/usr/src/service
      - ../node_modules:/usr/src/service/node_modules
    environment:
      - NODE_ENV=development
      - LOCAL_USER_ID=$LOCAL_USER_ID
      - DOCKER_NETWORK_URL=$DOCKER_NETWORK_URL
    working_dir: /usr/src/service
  suite-install:
    extends:
      service: suite-base
    command: bash -c "yarn && yarn build:libs"
